import './js/loaders';
import './js/progress-bar';
import './js/swiper';
import './js/posts/posts';
import './js/forgetForm/validate-form';
import './js/current-year';
import './js/scrool';
import './js/close';
import './js/forgetForm/actions';
